services:
  - type: web
    name: landingpage
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input"
    startCommand: "gunicorn yourproject.wsgi"
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bingpot-django-render
          property: connectionString
