# Generated by Django 3.2.3 on 2021-08-01 10:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='backgroundPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=40)),
                ('altText', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=50)),
                ('altText', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('releaseDate', models.DateField(default=0)),
                ('trailer', models.CharField(max_length=50)),
                ('storyline', models.CharField(max_length=120)),
                ('runtime', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('actors', models.ManyToManyField(blank=True, related_name='get_actors', to='movie.Actor')),
                ('backgroundPhoto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_background', to='movie.backgroundphoto')),
                ('categories', models.ManyToManyField(blank=True, related_name='list_categories', to='movie.Category')),
                ('directors', models.ManyToManyField(blank=True, related_name='get_directors', to='movie.Director')),
                ('photo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_pictures', to='movie.photo')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_comments', to='movie.movie')),
            ],
        ),
    ]
