# Generated by Django 3.2.3 on 2021-08-01 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='get_type', to='movie.type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(default='Movie', max_length=15),
        ),
    ]
