# Generated by Django 3.2.3 on 2021-08-01 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_type_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='backgroundPhoto',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='photo',
        ),
        migrations.AddField(
            model_name='backgroundphoto',
            name='movie',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='get_background', to='movie.movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='movie',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='get_pictures', to='movie.movie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='storyline',
            field=models.CharField(max_length=600),
        ),
    ]
