# Generated by Django 3.2.3 on 2021-08-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundphoto',
            name='image',
            field=models.CharField(max_length=350),
        ),
    ]
