# Generated by Django 3.2.3 on 2021-08-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_backgroundphoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tagline',
            field=models.CharField(default='Put on a happy face', max_length=150),
            preserve_default=False,
        ),
    ]
