# Generated by Django 3.2.3 on 2024-06-18 08:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20210803_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3),
        ),
    ]
