# Generated by Django 4.2.13 on 2024-07-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_movie_imdb_rating'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['imdb_rating'], name='movie_movie_imdb_ra_5d0e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['releaseDate'], name='movie_movie_release_26dcde_idx'),
        ),
    ]
